In [1]:
a = {"a":1,"b":2}
len(a)


2

In [4]:
import numpy as np
intercept = np.ones((1, 1))
intercept

array([[1.]])

In [2]:
import numpy as np
a = [1,2,3]

x = np.array(a).reshape(1,-1)
# intercept = np.ones((1, 1))
X_train   = np.concatenate(([[1]], x), axis=1)


In [3]:
x

array([[1, 2, 3]])

In [6]:
X_train

array([[1, 1, 2, 3]])